server.port=8080
spring.application.name=kripta-backend

# PostgreSQL via variaveis de ambiente
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/kripta}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
